lab_app/urls.py
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    path('labs/new', views.new_lab, name='new_lab'),
    path('labs/<lab_id>', views.lab_show, name='lab_show')
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.widgets import TinyMCE

# Create your models here.

class Lab(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    start_date = models.DateField()
    due_date = models.DateField()
    users = models.ManyToManyField(User)
    completed = models.BooleanField(default=False)

    class Meta: 
        verbose_name_plural = 'Labs'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        print('in save')
        todos = Todo.objects.filter(lab=self, completed=False)
        print(todos, self.id)
        print(len(todos) == 0 and self.id is not None)
        if len(todos) == 0 and self.id: 
            self.completed = True
        super(Lab, self).save(*args, **kwargs)

class Todo(models.Model):
    title = models.CharField(max_length=50)
    completed = models.BooleanField(default=False)
    lab = models.ForeignKey(Lab, default=1, verbose_name=("Lab"), on_delete=models.SET_DEFAULT)
    
    class Meta: 
        verbose_name_plural = 'Todos'

    def __str__(self):
        return self.title

main/forms.py
from django import forms
from .models import Lab, Todo
from django.forms import inlineformset_factory


class LabForm(forms.ModelForm):
    title = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea)
    start_date = forms.DateField(widget=forms.SelectDateWidget)
    due_date = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Lab
        fields = ['title', 'description', 'start_date', 'due_date']

    # def __init__(self, *args, **kwargs):
    #     super(LabForm, self).__init__(*args, **kwargs)
    #     self.fields['start_date'].widget = widgets.AdminSplitDateTime()
    #     self.fields['due_date'].widget = widgets.AdminSplitDateTime()

class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = ['title']

class TodoCheckboxForm(forms.Form):

    # todos = forms.ModelMultipleChoiceField(
    #                     widget = forms.CheckboxSelectMultiple,
    #                     queryset = Todo.objects.all()
    # #            )

    # todos = forms.choi

    # todos = forms.BooleanField

    # class Meta:
    #     model = Todos
    #     fields = ['todos']

    def __init__(self, lab, *args, **kwargs):
        super(TodoCheckboxForm, self).__init__(*args, **kwargs)
        # todos = Todo.objects.filter(lab=lab, completed=False)
        self.fields['todos'] = forms.ModelMultipleChoiceField(
                                widget = forms.CheckboxSelectMultiple,
                                queryset = Todo.objects.filter(lab=lab, completed=False)
                                )
        
        




TodoFormSet = inlineformset_factory(Lab, Todo, form=TodoForm)

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import LabForm, TodoForm, TodoFormSet, TodoCheckboxForm
from django.forms import formset_factory
from django.forms import modelformset_factory
from .models import Todo, Lab
from django.db.models import Q
# Create your views here.

def homepage(request):
    if request.user.is_authenticated:
        completed = Lab.objects.filter(users=request.user, completed=True)
        incompleted = Lab.objects.filter(users=request.user, completed=False).order_by('due_date')
        print(incompleted)
        return render(request, 
                    'main/homepage.html',
                    context={'completed': completed, 'incompleted': incompleted,
                            'logged_in': True})
    else: 
        return render(request,
                      'main/homepage.html', 
                      {'logged_in': False})

def signup(request):
    if request.method == "POST":  
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"New Account Created: {username}")
            login(request, user)
            return redirect('main:homepage')
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}:{form.error_messages[msg]}")

    form = UserCreationForm
    return render(request, 
                  'main/signup.html',
                  context={'form': form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f'You are now logged in as {username}')
                return redirect('main:homepage')
            else:
                messages.error(request, 'Invalid username or password')
        else: 
            messages.error(request, 'Invalid username or password. Likely missing a field.')
   
    form = AuthenticationForm
    return render(request, 
                  'main/login.html',
                  {'form': form})


def logout_request(request):
    logout(request)
    messages.info(request, 'Logged out successfully')
    return redirect('main:homepage')

def new_lab(request):
    todo_formset = formset_factory(TodoForm)
    # todo_formset = modelformset_factory(Todo, fields=('title',))
    if request.method == "POST":
        form = LabForm(request.POST)
        todos_form = todo_formset(request.POST)
        if form.is_valid() & todos_form.is_valid():
            lab = form.save()
            lab.users.add(request.user)
           
            for todo_f in todos_form:
                if todo_f.is_valid():
                    todo = todo_f.save()
                    lab.todo_set.add(todo)
            return redirect('main:homepage')
        else: 
            for msg in form.error_messages:
                messages.error(request, f"{msg}:{form.error_messages[msg]}")
    form = LabForm
    return render(request,
                  'main/labs/new.html',
                  {'form': form,
                    'todo_form': todo_formset
                  })
        
def lab_show(request, lab_id):
    lab = Lab.objects.get(pk=lab_id)
    completed = Todo.objects.filter(Q(lab__pk=lab_id) & Q(completed=True))
    todos = Todo.objects.filter(Q(lab__pk=lab_id) & Q(completed=False))



    checkbox_form = TodoCheckboxForm(lab)

    if request.method == "POST":
        form = TodoCheckboxForm(lab, request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            for todo in form.cleaned_data['todos']:
                todo.completed = True
                todo.save()
            

        lab.save()
        return redirect('main:homepage')

    return render(request, 'main/labs/show.html', 
                    context={'lab':lab, 'completed':completed, 'todos': todos, 'form': checkbox_form} )

main/templates/main/homepage.html
{% extends "main/main_html.html" %}

{% block content %}
<div class='container'>
    {% if logged_in == True%}
        <a href='/labs/new' class='btn btn-primary'> Add Lab</a> <br> <br>
        <h3> Completed Labs </h3>
        <hr>
        <div class='row'>
            {% for lab in completed %}
            <div class='col-md-4'>
                <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                    <div class="card-header">{{  lab.title }}</div>
                    <div class="card-body">
                        <h5 class="card-title">Due: {{ lab.due_date }}</h5>
                        <p class="card-text">{{ lab.description }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <h3> Labs to be completed </h3>
        <hr>
        <div class='row'>
            {% for lab in incompleted %}
            <div class='col-md-4'>
                    <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                        <div class="card-header">{{  lab.title }}</div>
                        <div class="card-body">
                            <h5 class="card-title">Due: {{ lab.due_date }}</h5>
                            <p class="card-text">{{ lab.description }}</p>
                            <a href={% url 'main:lab_show' lab_id=lab.id %} class="btn btn-light">View this lab.</a>
                        </div>
                    </div>
                </div>
 
            {% endfor %}
         </div>
        
    {% else %}
        <h3> Please log in to use this app. </h3>
    {% endif %}
</div>
{% endblock %}

main/templates/main/includes/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success'%}
           <div class="alert alert-success" role="alert">
                <h4 class="alert-heading">{{message}}</h4>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            </div>
        {% elif message.tags == 'error'%}
           <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading">{{message}}</h4>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            </div>        
        {% endif %}
    {% endfor %}
{% endif %}

main/templates/main/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
        <li class="nav-item active">
            <a class="nav-link" href="/logout"> Log out <span class="sr-only">(current)</span></a>
        </li>
      {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="/signup"> Sign Up <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
      {% endif %}
      <li class="nav-item">
          <a class="nav-link" href='/' data-toggle="modal" data-target="#exampleModalCenter">
              Help <span class="sr-only">(current)</span>
          </a>
      </li>
    </ul>
  </div>

  
 
    
    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">How to use this app.</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Each user has many labs that have many todo items. <br>
            Once you are logged in, you can create a lab. <br>
            In the new lab form, you can add as many todo items as needed. <br>
            Completed labs are displayed as green while incomplete labs are red. <br>
            When a todo item for a lab is completed, click on the lab and check the task.<br>
            Once a lab has all of its todo items completed, it will be displayed in green.<br>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
</nav>

main/templates/main/labs/new.html
{% extends 'main/main_html.html' %}

{% block content %}
    <div class=container>
    <form method="POST" action='/labs/new'>
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}

        <h4> What must be completed in this lab? </h4>
        {{ todo_form.management_form }}
        <div id="form_set">
            {% for form in todo_form.forms %}
                <table class='no_error'>
                    {{ form.as_table }}
                </table>
            {% endfor %}
        </div>
        <input type="button" value="Add Todos" id="add_more">
        <div id="empty_form" style="display:none">
            <table class='no_error'>
                {{ todo_form.empty_form.as_table }}
            </table>
        </div>
        <button class='btn' type='submit'> Create Lab </button>
    </form>
    </div>
{% endblock %}

main/templates/main/labs/show.html

{% extends 'main/main_html.html' %}

{% block content %}
    <h3> {{ lab }} </h3>

    <h4> Completed Tasks </h4>
    {% for task in completed %}    
        {{ task }} <br>
    {% endfor %}
    <br>
    <h4> To Be Completed</h4>
    <!-- <form method="POST">
        {% csrf_token %}
        {% for todo in todos %}
            <input id={{todo.id}} type="checkbox"> {{todo}} </input> <br>
        {% endfor %}
        <button type="submit" > Submit Changes </button>
    </form> -->

    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit" > Submit Changes </button>
    </form>


{% endblock %}

main/templates/main/login.html
{% extends "main/main_html.html" %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class='btn' style='background-color: darkred' type='submit'> Login </button>
    </form>

    If you don't already have an account, <a href='/login'><strong>register</strong></a> instead.
{% endblock %}

main/templates/main/main_html.html
<head>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <script type="text/javascript" src="{% static 'main/todo_script.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

    {% include 'main/includes/navbar.html' %}

    {% include 'main/includes/messages.html' %}

        <br>
        {% block content %}
        {% endblock %}
    </div>


main/templates/main/signup.html
{% extends "main/main_html.html" %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class='btn' style='background-color: lightblue' type='submit'> Register</button>
    </form>

    If you already have an account, <a href='/login'><strong>login</strong></a> instead.
{% endblock %}

main/templates/main/todos/new.html
{% extends 'main/main_html.html' %}
{% load static %}


{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button class='btn' type='submit'> Create Lab </button>
    </form>

{% endblock %}